// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sniffer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sniffer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SnifferQuery_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SnifferQuery_reflection_ = NULL;
const ::google::protobuf::Descriptor* SnifferResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SnifferResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* SnifferResponse_Timeval_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SnifferResponse_Timeval_reflection_ = NULL;
const ::google::protobuf::Descriptor* SnifferResponse_RSSIRecord_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SnifferResponse_RSSIRecord_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* QueryType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ResponseType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SnifferStatus_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_sniffer_2eproto() {
  protobuf_AddDesc_sniffer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sniffer.proto");
  GOOGLE_CHECK(file != NULL);
  SnifferQuery_descriptor_ = file->message_type(0);
  static const int SnifferQuery_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferQuery, type_),
  };
  SnifferQuery_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SnifferQuery_descriptor_,
      SnifferQuery::default_instance_,
      SnifferQuery_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferQuery, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferQuery, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SnifferQuery));
  SnifferResponse_descriptor_ = file->message_type(1);
  static const int SnifferResponse_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, valid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, ts_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, rssi_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, accum_period_),
  };
  SnifferResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SnifferResponse_descriptor_,
      SnifferResponse::default_instance_,
      SnifferResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SnifferResponse));
  SnifferResponse_Timeval_descriptor_ = SnifferResponse_descriptor_->nested_type(0);
  static const int SnifferResponse_Timeval_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_Timeval, tv_sec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_Timeval, tv_usec_),
  };
  SnifferResponse_Timeval_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SnifferResponse_Timeval_descriptor_,
      SnifferResponse_Timeval::default_instance_,
      SnifferResponse_Timeval_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_Timeval, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_Timeval, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SnifferResponse_Timeval));
  SnifferResponse_RSSIRecord_descriptor_ = SnifferResponse_descriptor_->nested_type(1);
  static const int SnifferResponse_RSSIRecord_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_RSSIRecord, mac_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_RSSIRecord, rssi_),
  };
  SnifferResponse_RSSIRecord_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SnifferResponse_RSSIRecord_descriptor_,
      SnifferResponse_RSSIRecord::default_instance_,
      SnifferResponse_RSSIRecord_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_RSSIRecord, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnifferResponse_RSSIRecord, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SnifferResponse_RSSIRecord));
  QueryType_descriptor_ = file->enum_type(0);
  ResponseType_descriptor_ = file->enum_type(1);
  SnifferStatus_descriptor_ = file->enum_type(2);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sniffer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SnifferQuery_descriptor_, &SnifferQuery::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SnifferResponse_descriptor_, &SnifferResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SnifferResponse_Timeval_descriptor_, &SnifferResponse_Timeval::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SnifferResponse_RSSIRecord_descriptor_, &SnifferResponse_RSSIRecord::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sniffer_2eproto() {
  delete SnifferQuery::default_instance_;
  delete SnifferQuery_reflection_;
  delete SnifferResponse::default_instance_;
  delete SnifferResponse_reflection_;
  delete SnifferResponse_Timeval::default_instance_;
  delete SnifferResponse_Timeval_reflection_;
  delete SnifferResponse_RSSIRecord::default_instance_;
  delete SnifferResponse_RSSIRecord_reflection_;
}

void protobuf_AddDesc_sniffer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rsniffer.proto\"6\n\014SnifferQuery\022&\n\004type\030"
    "\001 \002(\0162\n.QueryType:\014DATA_REQUEST\"\244\002\n\017Snif"
    "ferResponse\022!\n\004type\030\001 \002(\0162\r.ResponseType"
    ":\004DATA\022\r\n\005valid\030\002 \001(\010\022$\n\002ts\030\003 \001(\0132\030.Snif"
    "ferResponse.Timeval\022.\n\trssi_data\030\004 \003(\0132\033"
    ".SnifferResponse.RSSIRecord\022\036\n\006status\030\005 "
    "\001(\0162\016.SnifferStatus\022\024\n\014accum_period\030\006 \001("
    "\005\032*\n\007Timeval\022\016\n\006tv_sec\030\001 \001(\003\022\017\n\007tv_usec\030"
    "\002 \001(\003\032\'\n\nRSSIRecord\022\013\n\003mac\030\001 \001(\014\022\014\n\004rssi"
    "\030\002 \001(\005*1\n\tQueryType\022\022\n\016STATUS_REQUEST\020\000\022"
    "\020\n\014DATA_REQUEST\020\001*$\n\014ResponseType\022\010\n\004DAT"
    "A\020\000\022\n\n\006STATUS\020\001*6\n\rSnifferStatus\022\023\n\017SNIF"
    "FING_STOPED\020\000\022\020\n\014SNIFFING_RUN\020\001B\030\n\014sniff"
    "er_protB\010prot_buf", 537);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sniffer.proto", &protobuf_RegisterTypes);
  SnifferQuery::default_instance_ = new SnifferQuery();
  SnifferResponse::default_instance_ = new SnifferResponse();
  SnifferResponse_Timeval::default_instance_ = new SnifferResponse_Timeval();
  SnifferResponse_RSSIRecord::default_instance_ = new SnifferResponse_RSSIRecord();
  SnifferQuery::default_instance_->InitAsDefaultInstance();
  SnifferResponse::default_instance_->InitAsDefaultInstance();
  SnifferResponse_Timeval::default_instance_->InitAsDefaultInstance();
  SnifferResponse_RSSIRecord::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sniffer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sniffer_2eproto {
  StaticDescriptorInitializer_sniffer_2eproto() {
    protobuf_AddDesc_sniffer_2eproto();
  }
} static_descriptor_initializer_sniffer_2eproto_;
const ::google::protobuf::EnumDescriptor* QueryType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QueryType_descriptor_;
}
bool QueryType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ResponseType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResponseType_descriptor_;
}
bool ResponseType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SnifferStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SnifferStatus_descriptor_;
}
bool SnifferStatus_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int SnifferQuery::kTypeFieldNumber;
#endif  // !_MSC_VER

SnifferQuery::SnifferQuery()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SnifferQuery::InitAsDefaultInstance() {
}

SnifferQuery::SnifferQuery(const SnifferQuery& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SnifferQuery::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SnifferQuery::~SnifferQuery() {
  SharedDtor();
}

void SnifferQuery::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SnifferQuery::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SnifferQuery::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SnifferQuery_descriptor_;
}

const SnifferQuery& SnifferQuery::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sniffer_2eproto();
  return *default_instance_;
}

SnifferQuery* SnifferQuery::default_instance_ = NULL;

SnifferQuery* SnifferQuery::New() const {
  return new SnifferQuery;
}

void SnifferQuery::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SnifferQuery::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .QueryType type = 1 [default = DATA_REQUEST];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::QueryType_IsValid(value)) {
            set_type(static_cast< ::QueryType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SnifferQuery::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .QueryType type = 1 [default = DATA_REQUEST];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SnifferQuery::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .QueryType type = 1 [default = DATA_REQUEST];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SnifferQuery::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .QueryType type = 1 [default = DATA_REQUEST];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SnifferQuery::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SnifferQuery* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SnifferQuery*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SnifferQuery::MergeFrom(const SnifferQuery& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SnifferQuery::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SnifferQuery::CopyFrom(const SnifferQuery& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnifferQuery::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void SnifferQuery::Swap(SnifferQuery* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SnifferQuery::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SnifferQuery_descriptor_;
  metadata.reflection = SnifferQuery_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SnifferResponse_Timeval::kTvSecFieldNumber;
const int SnifferResponse_Timeval::kTvUsecFieldNumber;
#endif  // !_MSC_VER

SnifferResponse_Timeval::SnifferResponse_Timeval()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SnifferResponse_Timeval::InitAsDefaultInstance() {
}

SnifferResponse_Timeval::SnifferResponse_Timeval(const SnifferResponse_Timeval& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SnifferResponse_Timeval::SharedCtor() {
  _cached_size_ = 0;
  tv_sec_ = GOOGLE_LONGLONG(0);
  tv_usec_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SnifferResponse_Timeval::~SnifferResponse_Timeval() {
  SharedDtor();
}

void SnifferResponse_Timeval::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SnifferResponse_Timeval::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SnifferResponse_Timeval::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SnifferResponse_Timeval_descriptor_;
}

const SnifferResponse_Timeval& SnifferResponse_Timeval::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sniffer_2eproto();
  return *default_instance_;
}

SnifferResponse_Timeval* SnifferResponse_Timeval::default_instance_ = NULL;

SnifferResponse_Timeval* SnifferResponse_Timeval::New() const {
  return new SnifferResponse_Timeval;
}

void SnifferResponse_Timeval::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    tv_sec_ = GOOGLE_LONGLONG(0);
    tv_usec_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SnifferResponse_Timeval::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 tv_sec = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &tv_sec_)));
          set_has_tv_sec();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_tv_usec;
        break;
      }

      // optional int64 tv_usec = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_tv_usec:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &tv_usec_)));
          set_has_tv_usec();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SnifferResponse_Timeval::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int64 tv_sec = 1;
  if (has_tv_sec()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->tv_sec(), output);
  }

  // optional int64 tv_usec = 2;
  if (has_tv_usec()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->tv_usec(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SnifferResponse_Timeval::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int64 tv_sec = 1;
  if (has_tv_sec()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->tv_sec(), target);
  }

  // optional int64 tv_usec = 2;
  if (has_tv_usec()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->tv_usec(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SnifferResponse_Timeval::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 tv_sec = 1;
    if (has_tv_sec()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->tv_sec());
    }

    // optional int64 tv_usec = 2;
    if (has_tv_usec()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->tv_usec());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SnifferResponse_Timeval::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SnifferResponse_Timeval* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SnifferResponse_Timeval*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SnifferResponse_Timeval::MergeFrom(const SnifferResponse_Timeval& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tv_sec()) {
      set_tv_sec(from.tv_sec());
    }
    if (from.has_tv_usec()) {
      set_tv_usec(from.tv_usec());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SnifferResponse_Timeval::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SnifferResponse_Timeval::CopyFrom(const SnifferResponse_Timeval& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnifferResponse_Timeval::IsInitialized() const {

  return true;
}

void SnifferResponse_Timeval::Swap(SnifferResponse_Timeval* other) {
  if (other != this) {
    std::swap(tv_sec_, other->tv_sec_);
    std::swap(tv_usec_, other->tv_usec_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SnifferResponse_Timeval::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SnifferResponse_Timeval_descriptor_;
  metadata.reflection = SnifferResponse_Timeval_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SnifferResponse_RSSIRecord::kMacFieldNumber;
const int SnifferResponse_RSSIRecord::kRssiFieldNumber;
#endif  // !_MSC_VER

SnifferResponse_RSSIRecord::SnifferResponse_RSSIRecord()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SnifferResponse_RSSIRecord::InitAsDefaultInstance() {
}

SnifferResponse_RSSIRecord::SnifferResponse_RSSIRecord(const SnifferResponse_RSSIRecord& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SnifferResponse_RSSIRecord::SharedCtor() {
  _cached_size_ = 0;
  mac_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  rssi_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SnifferResponse_RSSIRecord::~SnifferResponse_RSSIRecord() {
  SharedDtor();
}

void SnifferResponse_RSSIRecord::SharedDtor() {
  if (mac_ != &::google::protobuf::internal::kEmptyString) {
    delete mac_;
  }
  if (this != default_instance_) {
  }
}

void SnifferResponse_RSSIRecord::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SnifferResponse_RSSIRecord::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SnifferResponse_RSSIRecord_descriptor_;
}

const SnifferResponse_RSSIRecord& SnifferResponse_RSSIRecord::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sniffer_2eproto();
  return *default_instance_;
}

SnifferResponse_RSSIRecord* SnifferResponse_RSSIRecord::default_instance_ = NULL;

SnifferResponse_RSSIRecord* SnifferResponse_RSSIRecord::New() const {
  return new SnifferResponse_RSSIRecord;
}

void SnifferResponse_RSSIRecord::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_mac()) {
      if (mac_ != &::google::protobuf::internal::kEmptyString) {
        mac_->clear();
      }
    }
    rssi_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SnifferResponse_RSSIRecord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes mac = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_mac()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_rssi;
        break;
      }

      // optional int32 rssi = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_rssi:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rssi_)));
          set_has_rssi();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SnifferResponse_RSSIRecord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bytes mac = 1;
  if (has_mac()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->mac(), output);
  }

  // optional int32 rssi = 2;
  if (has_rssi()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->rssi(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SnifferResponse_RSSIRecord::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bytes mac = 1;
  if (has_mac()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->mac(), target);
  }

  // optional int32 rssi = 2;
  if (has_rssi()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->rssi(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SnifferResponse_RSSIRecord::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes mac = 1;
    if (has_mac()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->mac());
    }

    // optional int32 rssi = 2;
    if (has_rssi()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->rssi());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SnifferResponse_RSSIRecord::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SnifferResponse_RSSIRecord* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SnifferResponse_RSSIRecord*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SnifferResponse_RSSIRecord::MergeFrom(const SnifferResponse_RSSIRecord& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mac()) {
      set_mac(from.mac());
    }
    if (from.has_rssi()) {
      set_rssi(from.rssi());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SnifferResponse_RSSIRecord::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SnifferResponse_RSSIRecord::CopyFrom(const SnifferResponse_RSSIRecord& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnifferResponse_RSSIRecord::IsInitialized() const {

  return true;
}

void SnifferResponse_RSSIRecord::Swap(SnifferResponse_RSSIRecord* other) {
  if (other != this) {
    std::swap(mac_, other->mac_);
    std::swap(rssi_, other->rssi_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SnifferResponse_RSSIRecord::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SnifferResponse_RSSIRecord_descriptor_;
  metadata.reflection = SnifferResponse_RSSIRecord_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SnifferResponse::kTypeFieldNumber;
const int SnifferResponse::kValidFieldNumber;
const int SnifferResponse::kTsFieldNumber;
const int SnifferResponse::kRssiDataFieldNumber;
const int SnifferResponse::kStatusFieldNumber;
const int SnifferResponse::kAccumPeriodFieldNumber;
#endif  // !_MSC_VER

SnifferResponse::SnifferResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SnifferResponse::InitAsDefaultInstance() {
  ts_ = const_cast< ::SnifferResponse_Timeval*>(&::SnifferResponse_Timeval::default_instance());
}

SnifferResponse::SnifferResponse(const SnifferResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SnifferResponse::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  valid_ = false;
  ts_ = NULL;
  status_ = 0;
  accum_period_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SnifferResponse::~SnifferResponse() {
  SharedDtor();
}

void SnifferResponse::SharedDtor() {
  if (this != default_instance_) {
    delete ts_;
  }
}

void SnifferResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SnifferResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SnifferResponse_descriptor_;
}

const SnifferResponse& SnifferResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sniffer_2eproto();
  return *default_instance_;
}

SnifferResponse* SnifferResponse::default_instance_ = NULL;

SnifferResponse* SnifferResponse::New() const {
  return new SnifferResponse;
}

void SnifferResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 0;
    valid_ = false;
    if (has_ts()) {
      if (ts_ != NULL) ts_->::SnifferResponse_Timeval::Clear();
    }
    status_ = 0;
    accum_period_ = 0;
  }
  rssi_data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SnifferResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ResponseType type = 1 [default = DATA];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ResponseType_IsValid(value)) {
            set_type(static_cast< ::ResponseType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_valid;
        break;
      }

      // optional bool valid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_valid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &valid_)));
          set_has_valid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_ts;
        break;
      }

      // optional .SnifferResponse.Timeval ts = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ts:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ts()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_rssi_data;
        break;
      }

      // repeated .SnifferResponse.RSSIRecord rssi_data = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_rssi_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_rssi_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_rssi_data;
        if (input->ExpectTag(40)) goto parse_status;
        break;
      }

      // optional .SnifferStatus status = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_status:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::SnifferStatus_IsValid(value)) {
            set_status(static_cast< ::SnifferStatus >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_accum_period;
        break;
      }

      // optional int32 accum_period = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_accum_period:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &accum_period_)));
          set_has_accum_period();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SnifferResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ResponseType type = 1 [default = DATA];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional bool valid = 2;
  if (has_valid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->valid(), output);
  }

  // optional .SnifferResponse.Timeval ts = 3;
  if (has_ts()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->ts(), output);
  }

  // repeated .SnifferResponse.RSSIRecord rssi_data = 4;
  for (int i = 0; i < this->rssi_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->rssi_data(i), output);
  }

  // optional .SnifferStatus status = 5;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->status(), output);
  }

  // optional int32 accum_period = 6;
  if (has_accum_period()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->accum_period(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SnifferResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ResponseType type = 1 [default = DATA];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional bool valid = 2;
  if (has_valid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->valid(), target);
  }

  // optional .SnifferResponse.Timeval ts = 3;
  if (has_ts()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->ts(), target);
  }

  // repeated .SnifferResponse.RSSIRecord rssi_data = 4;
  for (int i = 0; i < this->rssi_data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->rssi_data(i), target);
  }

  // optional .SnifferStatus status = 5;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->status(), target);
  }

  // optional int32 accum_period = 6;
  if (has_accum_period()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->accum_period(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SnifferResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ResponseType type = 1 [default = DATA];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional bool valid = 2;
    if (has_valid()) {
      total_size += 1 + 1;
    }

    // optional .SnifferResponse.Timeval ts = 3;
    if (has_ts()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ts());
    }

    // optional .SnifferStatus status = 5;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }

    // optional int32 accum_period = 6;
    if (has_accum_period()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->accum_period());
    }

  }
  // repeated .SnifferResponse.RSSIRecord rssi_data = 4;
  total_size += 1 * this->rssi_data_size();
  for (int i = 0; i < this->rssi_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->rssi_data(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SnifferResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SnifferResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SnifferResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SnifferResponse::MergeFrom(const SnifferResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  rssi_data_.MergeFrom(from.rssi_data_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_valid()) {
      set_valid(from.valid());
    }
    if (from.has_ts()) {
      mutable_ts()->::SnifferResponse_Timeval::MergeFrom(from.ts());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_accum_period()) {
      set_accum_period(from.accum_period());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SnifferResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SnifferResponse::CopyFrom(const SnifferResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnifferResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void SnifferResponse::Swap(SnifferResponse* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(valid_, other->valid_);
    std::swap(ts_, other->ts_);
    rssi_data_.Swap(&other->rssi_data_);
    std::swap(status_, other->status_);
    std::swap(accum_period_, other->accum_period_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SnifferResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SnifferResponse_descriptor_;
  metadata.reflection = SnifferResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
